name: cargo-build
on: [push]
jobs:
  tests:
    name: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features
  build-linux:
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: gherkin-converter-linux
          path: target/release/gherkin-converter
  build-macos:
    runs-on: macos-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: gherkin-converter-macos
          path: target/release/gherkin-converter
  create-package:
    runs-on: ubuntu-latest
    needs: [build-linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gherkin-converter-linux
      - uses: actions/download-artifact@v3
        with:
          name: gherkin-converter-macos
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            gherkin-converter-linux
            gherkin-converter-macos
