name: cargo-build
on: [push]
jobs:
  tests:
    name: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --all-features
  build-linux:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: x86_64-unknown-linux-musl
      - run: cargo build --target=x86_64-unknown-linux-musl --release
      - run: mv target/x86_64-unknown-linux-musl/release/gherkin-converter gherkin-converter-linux
      - uses: actions/upload-artifact@v3
        with:
          name: gherkin-converter-linux
          path: gherkin-converter-linux
  build-macos:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    needs: [tests]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo build --release
      - run: mv target/release/gherkin-converter gherkin-converter-macos
      - uses: actions/upload-artifact@v3
        with:
          name: gherkin-converter-macos
          path: gherkin-converter-macos
  create-package:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: gherkin-converter-linux
      - uses: actions/download-artifact@v3
        with:
          name: gherkin-converter-macos
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            gherkin-converter-linux
            gherkin-converter-macos
